name       : go-md2man
version    : 2.0.2
release    : 3
source     :
    - https://github.com/cpuguy83/go-md2man/archive/v2.0.2.tar.gz : 2f52e37101ea2734b02f2b54a53c74305b95b3a9a27792fdac962b5354aa3e4a
license    : MIT
component  : system.utils
summary    : A utility to convert md-files to man pages
description: |
    A utility to convert md-files to man pages
builddeps  :
    - golang
build      : |
    export GOFLAGS="-buildmode=pie -mod=vendor -trimpath"
    go build -o go-md2man .

    # Bonus, this also checks that go-md2man is working:
    ./go-md2man -in=go-md2man.1.md -out=go-md2man.1
install    : |
    install -Dm00755 go-md2man $installdir/usr/bin/go-md2man
    install -Dm00644 go-md2man.1 $installdir/usr/share/man/man1/go-md2man.1
